import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  safelist: [
    // Dynamic swatches + shadows rendered by the showcase
    { pattern: /^bg-(brand|neutral|green|red|blue|orange|pink|cream|ice|feedback)-/ },
    { pattern: /^shadow-(xs|sm|md|lg|xl|card|dropdown|modal)$/ },
    { pattern: /^rounded-(none|xs|sm|md|lg|xl|2xl|full)$/ },
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1600px",
    },
    extend: {
      colors: {
        // Primitive — Neutral (dark-first scale: 0=black → 1000=white)
        neutral: {
          0: "#000000",
          50: "#070707",
          100: "#121212",
          150: "#141517",
          200: "#1e1e1e",
          300: "#27272a",
          400: "#38383d",
          500: "#515158",
          600: "#67676d",
          700: "#808089",
          800: "#a6a6b0",
          850: "#c4c4cf",
          900: "#dddde3",
          950: "#f5f5fa",
          1000: "#ffffff",
        },
        // Primitive — Brand (cream scale — product signature)
        brand: {
          50: "#fffaf0",
          100: "#fff3db",
          200: "#fde7c0",
          300: "#fdebcf",
          400: "#e7d3a8",
          500: "#cabb9b",
          600: "#b4ab97",
          700: "#8f8672",
          800: "#6b634e",
          900: "#453f2f",
        },
        green: {
          100: "#d1fae5",
          200: "#a7f3d0",
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
          700: "#047857",
        },
        red: {
          100: "#fde4e0",
          200: "#fac3b8",
          500: "#ce624a",
          600: "#b04d37",
          700: "#8f3a27",
          800: "#6b2719",
        },
        blue: { 500: "#0090ff" },
        orange: { 300: "#ffd774", 400: "#f1be59", 500: "#fb7e16" },
        pink: { 500: "#ff6d9c" },
        cream: { 200: "#ffe8c9", 300: "#ffe2c4" },
        ice: { 200: "#e8f3ff", 300: "#c9d4ff" },

        // Semantic — use these in components. Driven by CSS variables
        // so we can theme later via data-theme attr.
        bg: {
          DEFAULT: "rgb(var(--bg) / <alpha-value>)",
          subtle: "rgb(var(--bg-subtle) / <alpha-value>)",
          muted: "rgb(var(--bg-muted) / <alpha-value>)",
        },
        surface: {
          DEFAULT: "rgb(var(--surface) / <alpha-value>)",
          elevated: "rgb(var(--surface-elevated) / <alpha-value>)",
          strong: "rgb(var(--surface-strong) / <alpha-value>)",
          overlay: "rgb(var(--surface-overlay) / <alpha-value>)",
        },
        text: {
          primary: "rgb(var(--text-primary) / <alpha-value>)",
          secondary: "rgb(var(--text-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--text-tertiary) / <alpha-value>)",
          inverse: "rgb(var(--text-inverse) / <alpha-value>)",
          "on-primary": "rgb(var(--text-on-primary) / <alpha-value>)",
          disabled: "rgb(var(--text-disabled) / <alpha-value>)",
        },
        border: {
          subtle: "rgb(var(--border-subtle) / <alpha-value>)",
          DEFAULT: "rgb(var(--border-default) / <alpha-value>)",
          strong: "rgb(var(--border-strong) / <alpha-value>)",
          focus: "rgb(var(--border-focus) / <alpha-value>)",
          error: "rgb(var(--border-error) / <alpha-value>)",
          disabled: "rgb(var(--border-disabled) / <alpha-value>)",
        },
        action: {
          primary: {
            DEFAULT: "rgb(var(--action-primary) / <alpha-value>)",
            hover: "rgb(var(--action-primary-hover) / <alpha-value>)",
            pressed: "rgb(var(--action-primary-pressed) / <alpha-value>)",
          },
          secondary: {
            DEFAULT: "rgb(var(--action-secondary) / <alpha-value>)",
            hover: "rgb(var(--action-secondary-hover) / <alpha-value>)",
          },
          ghost: {
            hover: "rgb(var(--action-ghost-hover) / <alpha-value>)",
          },
          danger: {
            DEFAULT: "rgb(var(--action-danger) / <alpha-value>)",
            hover: "rgb(var(--action-danger-hover) / <alpha-value>)",
          },
        },
        feedback: {
          success: "rgb(var(--feedback-success) / <alpha-value>)",
          "success-subtle": "rgb(var(--feedback-success-subtle) / <alpha-value>)",
          warning: "rgb(var(--feedback-warning) / <alpha-value>)",
          error: "rgb(var(--feedback-error) / <alpha-value>)",
          info: "rgb(var(--feedback-info) / <alpha-value>)",
        },
        icon: {
          DEFAULT: "rgb(var(--icon-default) / <alpha-value>)",
          muted: "rgb(var(--icon-muted) / <alpha-value>)",
          inverse: "rgb(var(--icon-inverse) / <alpha-value>)",
        },
        disabled: {
          fill: "rgb(var(--disabled-fill) / <alpha-value>)",
          text: "rgb(var(--disabled-text) / <alpha-value>)",
        },
      },
      spacing: {
        "0": "0px",
        "0.5": "2px",
        "1": "4px",
        "1.5": "6px",
        "2": "8px",
        "2.5": "10px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "9": "36px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
      },
      borderRadius: {
        none: "0",
        xs: "2px",
        sm: "4px",
        DEFAULT: "8px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
      },
      borderWidth: {
        none: "0",
        hairline: "0.5px",
        DEFAULT: "1px",
        thin: "1px",
        medium: "1.5px",
        thick: "2px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(0, 0, 0, 0.08)",
        sm: "0 3px 6px rgba(0, 0, 0, 0.12)",
        md: "0 4px 10px rgba(0, 0, 0, 0.16)",
        lg: "0 10px 20px rgba(0, 0, 0, 0.24)",
        xl: "0 18px 40px rgba(0, 0, 0, 0.32)",
        card: "0 2px 8px rgba(0, 0, 0, 0.16)",
        dropdown: "0 6px 16px rgba(0, 0, 0, 0.24)",
        modal: "0 16px 40px rgba(0, 0, 0, 0.40)",
        "focus-ring": "0 0 0 3px rgba(253, 235, 207, 0.24), 0 0 8px rgba(253, 235, 207, 0.4)",
        "focus-ring-error": "0 0 0 3px rgba(206, 98, 74, 0.24)",
        "inner-surface": "inset 0 0 4px rgba(0, 0, 0, 0.24)",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        // Display
        "display-lg": ["44px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-md": ["40px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-sm": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        // Heading
        h1: ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        h4: ["18px", { lineHeight: "24px", fontWeight: "600" }],
        h5: ["16px", { lineHeight: "24px", fontWeight: "600" }],
        h6: ["14px", { lineHeight: "20px", fontWeight: "600" }],
        // Title (Medium weight)
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        // Body
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        // Label
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "500" }],
        // Button (Bold)
        "button-lg": ["16px", { lineHeight: "24px", fontWeight: "700" }],
        "button-md": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "button-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        // Misc
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        overline: ["12px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" }],
        helper: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        error: ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      transitionDuration: {
        fast: "120ms",
        DEFAULT: "180ms",
        slow: "240ms",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-out": { from: { opacity: "1" }, to: { opacity: "0" } },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        spin: { to: { transform: "rotate(360deg)" } },
      },
      animation: {
        "fade-in": "fade-in 180ms ease-out",
        "fade-out": "fade-out 120ms ease-in",
        "slide-up": "slide-up 200ms cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scale-in 180ms cubic-bezier(0.16, 1, 0.3, 1)",
        "spin-slow": "spin 800ms linear infinite",
      },
    },
  },
  plugins: [],
} satisfies Config;
